# Generated by Django 2.0.2 on 2018-04-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_lesson_learn_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='learn_time',
        ),
        migrations.AddField(
            model_name='video',
            name='learn_time',
            field=models.IntegerField(default=0, verbose_name='学习时长（分钟）'),
        ),
    ]
