# Generated by Django 2.0.2 on 2018-04-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20180410_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_requirements',
            field=models.CharField(default='', max_length=300, verbose_name='课程须知'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_told',
            field=models.CharField(default='', max_length=300, verbose_name='讲师告知'),
        ),
    ]
